[package]
name = "tickets"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
eddsa = { tag = "v0.1.3", git = "https://github.com/noir-lang/eddsa" }
